### ISSUE TITLE
Which external CSS framework?

### ISSUE THREAD

**Issue by noah35becker** [noah35becker/fuzzy-enigma#7]
Decide on an external CSS framework other than Bootstrap to use for this project

**Comment by mnwana** [comment]
here are some options @noah35becker @claudiayile 
- https://tailwindcss.com/docs/installation/play-cdn 
- https://materializecss.com/
- https://semantic-ui.com/
- https://get.foundation/

**Comment by noah35becker** [comment]
**[](https://materializecss.com/)**

I like the look of this one a lot! We can use its Form/Select framework instead of jQuery UI for the dropdowns, and the color palette and other components look great

**Comment by noah35becker** [comment]
The responsive grid stuff is also good, similar to Bootstrap
